### ISSUE TITLE
yarn test fails. Can't find abi directory

### ISSUE THREAD

**Issue by samlaf** [yieldprotocol/vault-v2#399]
I git cloned, yarn installed, and running `yarn test` results in this error:

```
> yarn test                                                                                   (py39) 
yarn run v1.22.18
$ yarn build && hardhat test --show-stack-traces
$ rm -rf artifacts typechain && hardhat compile
Solidity 0.8.6 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support"

Compiling 147 files with 0.8.6
Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
  --> contracts/mocks/ConvexPoolMock.sol:30:42:
   |
30 |     function getReward(address _account, bool _claimExtras) public returns (bool) {
   |                                          ^^^^^^^^^^^^^^^^^


Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
  --> contracts/mocks/ConvexPoolMock.sol:53:40:
   |
53 |     function withdraw(uint256 _amount, bool _claim) public returns (bool) {
   |                                        ^^^^^^^^^^^


Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
  --> contracts/mocks/YvTokenMock.sol:20:41:
   |
20 |     function deposit(uint256 deposited, address to) public returns (uint256 minted) {
   |                                         ^^^^^^^^^^


Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
  --> contracts/other/notional/FCashMock.sol:37:50:
   |
37 |     function batchBalanceAction(address account, IBatchAction.BalanceAction[] calldata actions) external {
   |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Warning: Function state mutability can be restricted to pure
  --> contracts/mocks/ConvexPoolMock.sol:64:5:
   |
64 |     function extraRewardsLength() public view returns (uint256) {
   |     ^ (Relevant source part starts here and spans across multiple lines).


Warning: Function state mutability can be restricted to view
  --> contracts/oracles/yearn/YearnVaultMultiOracle.sol:85:5:
   |
85 |     function get(
   |     ^ (Relevant source part starts here and spans across multiple lines).


Warning: Function state mutability can be restricted to pure
  --> contracts/other/notional/NotionalJoin.sol:65:5:
   |
65 |     function supportsInterface(bytes4 interfaceID) external view returns (bool) {
   |     ^ (Relevant source part starts here and spans across multiple lines).


Warning: Function state mutability can be restricted to view
  --> contracts/other/notional/NotionalJoin.sol:73:5:
   |
73 |     function onERC1155Received(
   |     ^ (Relevant source part starts here and spans across multiple lines).


Warning: Function state mutability can be restricted to view
  --> contracts/other/notional/NotionalJoin.sol:85:5:
   |
85 |     function onERC1155BatchReceived(
   |     ^ (Relevant source part starts here and spans across multiple lines).


Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> contracts/foundry-tests/ChainlinkMultiOracle.t.sol:14:1:
   |
14 | contract ChainlinkMultiOracleTest is Test, TestConstants, AccessControl {
   | ^ (Relevant source part starts here and spans across multiple lines).


Compilation finished successfully
An unexpected error occurred:

Error: ENOENT: no such file or directory, stat '/home/samlaf/devel/abag/vault-v2/abi'
    at Object.statSync (node:fs:1527:3)
    at __node_internal_ (node:internal/fs/utils:767:8)
    at Object.rmdirSync (node:fs:1147:15)
    at OverriddenTaskDefinition._action (/home/samlaf/devel/abag/vault-v2/node_modules/hardhat-abi-exporter/index.js:41:8)
    at Environment._runTaskDefinition (/home/samlaf/devel/abag/vault-v2/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at OverriddenTaskDefinition._action (/home/samlaf/devel/abag/vault-v2/node_modules/hardhat-contract-sizer/index.js:100:3)
    at Environment._runTaskDefinition (/home/samlaf/devel/abag/vault-v2/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at OverriddenTaskDefinition._action (/home/samlaf/devel/abag/vault-v2/node_modules/hardhat-typechain/src/index.ts:33:7)
    at Environment._runTaskDefinition (/home/samlaf/devel/abag/vault-v2/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/samlaf/devel/abag/vault-v2/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/samlaf/devel/abag/vault-v2/abi'
}
(node:236788) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
error Command failed with exit code 1.
```

Am I supposed to run a command to generate the abi directory?

**Comment by alcueca** [comment]
Have you tried a newer node version (I use 14) or manually creating the `abi` folder?

**Comment by samlaf** [comment]
Sorry for the slow reply.
I can't even reproduce this today... using node 16, and everything is fine.
Maybe the code was changed?

There's a way to add an empty `abi` folder to a git repo, while excluding everything inside. I usually do this to avoid these kinds of mistakes. https://stackoverflow.com/a/5581995/4971151
